django/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_page, name='home'),
    path('create_room/', views.create_room, name='create_room'),
	path('send_game_invite/', views.send_game_invite, name='send_game_invite'),
    path('<str:slug>/', views.room, name='room'),
]

django/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('', include('home.urls')),
    path('chat/', include('chat.urls')),
    path('users/', include('users.urls')),
    path('', include('security.urls')),
]

# to access user uploaded images (profile picture)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_v, name='signup'),
    path('blocking/', views.blocking, name='blocking'),
    path('login/', views.login_v, name='login'),
    path('callback/', views.callback, name='callback'),
    path('logout/', views.logout_v, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<str:username>', views.profile, name='profile'),
	path('profile/edit/', views.editprofile, name='profile_edit'),
    path('profile/<str:username>/delete/', views.deleteprofile, name='profile_delete'),
    path('friend_request/', views.send_friend_request, name='friend_request'),
    path('friend_remove/', views.remove_friend, name='remove_friend'),
    path('cancel_friend_request/', views.cancel_friend_request, name='friend_request_cancel'),
    path('accept_friend_request/<str:friend_request_id>', views.accept_friend_request, name='friend_request_accept'),
    path('decline_friend_request/<str:friend_request_id>', views.decline_friend_request, name='friend_request_decline'),
]

django/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from PIL import Image
from django.conf import settings
from django.utils import timezone
from .helpers import pick_random_description

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    isstudent = models.BooleanField(default=False)
    wins = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    creation_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=False)
    description = models.CharField(default=pick_random_description())
    blocklist = models.ManyToManyField(User, blank=True, related_name="blocklist")

    def __str__(self):
        return f'{self.user.username} Profile'
    
    # resizes all large profile images
    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class FriendList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user")
    friends = models.ManyToManyField(User, blank=True, related_name="friends")

    def __str__(self):
        return self.user.username
    
    def add_friend(self, account):
        """
        Add a new friend
        """
        if account not in self.friends.all():
            self.friends.add(account)
            self.save()
    
    def remove_friend(self, account):
        """
        Remove friend
        """
        if account in self.friends.all():
            self.friends.remove(account)
    
    def unfriend(self, target):
        """
        Unfriend someone
        """
        my_friends_list = self # person terminating 
        my_friends_list.remove_friend(target)

        targets_friends_list = FriendList.objects.get(user=target)
        targets_friends_list.remove_friend(self.user)

    def is_mutual_friend(self, target):
        """
        Is this a friend
        """
        if target in self.friends.all():
            return True
        return False

class FriendRequest(models.Model):
    """
    A friend request consists of two main parts:
        1. SENDER:
            - Person sending the friend request
        2. RECEIVER:
            - Person receiving the friend request
    """
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver")
    is_active = models.BooleanField(blank=True, null=False, default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender.username
    
    def accept(self):
        """
        Accept a friend request
            Update both SENDER and RECEIVER friend lists
        """
        receiver_friend_list = FriendList.objects.get(user=self.receiver)
        if receiver_friend_list:
            receiver_friend_list.add_friend(self.sender)
            sender_friend_list = FriendList.objects.get(user=self.sender)
            if sender_friend_list:
                sender_friend_list.add_friend(self.receiver)
                self.is_active = False
                self.save()
    
    def decline(self):
        """
        Decline a friend request (sent to you)
            Is it "declined" by setting the "is_active" field to False
        """
        self.is_active = False
        self.save()
    
    def cancel(self):
        """
        Cancel a friend request (you sent)
            It is "cancelled" by setting the "is_active" field to False
        """
        self.is_active = False
        self.save()

django/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

django/users/views.py
import os, json
from urllib.parse import urlencode
from dotenv import load_dotenv
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import FriendList, FriendRequest
from .utils import Oauth42, get_friend_request_or_false
from .friend_request_status import FriendRequestStatus
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseBadRequest
from django.urls import reverse
from django.template.loader import render_to_string
from render_block import render_block_to_string
from django.middleware.csrf import get_token
from game.models import LeaderboardEntry

# Load environment variables
load_dotenv()

CLIENT_ID = os.getenv('CLIENT_ID')
CLIENT_SECRET = os.getenv('CLIENT_SECRET')
REDIRECT_URI = 'https://localhost/users/callback/'

# Define the FROMLOGIN and FROMSIGNUP variables
FROMLOGIN = 'd56b699830e77ba53855679cb1d252da'
FROMSIGNUP = '7d2abf2d0fa7c3a0c13236910f30bc43'

def build_authorize_uri(state_value):
    params = {
        'client_id': CLIENT_ID,
        'redirect_uri': REDIRECT_URI,
        'response_type': 'code',
        'scope': 'public',
        'state': state_value
    }
    return f"https://api.intra.42.fr/oauth/authorize?{urlencode(params)}"

# Update your views to use the new build_authorize_uri function
@require_http_methods(['GET', 'POST'])
def signup_v(request) -> HttpResponse:
    context = {
        'authorize_uri': build_authorize_uri(FROMSIGNUP),
        'show_alerts': True,
        'request': request
    }
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created! You are now able to log in.')
            context['form'] = AuthenticationForm()
            return render(request, 'users/login.html', context)
    else:
        form = UserRegisterForm()
    context['form'] = form

    return render(request, 'users/signup.html', context)

@require_http_methods(['GET', 'POST'])
def login_v(request) -> HttpResponse:
    context = {
        'authorize_uri': build_authorize_uri(FROMLOGIN),
        'show_alerts': True,
        'request': request
    }
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            user.profile.active = True
            login(request, user)
            context['request'] = request
            return render(request, 'home/welcome.html', context)
    else:
        form = AuthenticationForm()
    context['form'] = form
    return render(request, 'users/login.html', context)


"""
Callback for Oauth2 logic
--
catches tmp_code, exchanges it for an access token, use that
token to get user informations
"""
@require_GET
def callback(request) -> None:
    page_origin = request.GET.get('state')
    authorization_code = request.GET.get('code')
    if authorization_code is None:
        return HttpResponseBadRequest("Bad Request: Missing 'code' parameter")
    
    # exchange authorization code for access token
    o42 = Oauth42()
    token = o42.get_token(authorization_code)
    if token == None:
        messages.warning(request, f"Couldn't exchange code for access token.")
        return redirect('users:signup')

    # use token to request user data
    user_data = o42.get_user_data(token)
    if user_data == None:
        messages.warning(request, f'Error: Unable to login. Try signing-up. Probably 401 "Unauthorized"')
        return redirect('users:signup')
    username_42 = user_data.get('login')
    email_42 = user_data.get('email')

    # when user is in database
    if username_42 in str(User.objects.all()):
        known_user = User.objects.get(username=username_42)
        if known_user.profile.isstudent:
            known_user.profile.active = True
            login(request, known_user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home:welcome')
        else:
            if page_origin == FROMLOGIN:
                messages.warning(request, "The account you're trying to connect to was created without 42intra. Please enter your credentials to log in.")
                return redirect('users:login')
            else:
                messages.warning(request, f'The username <strong>{username_42}</strong> already exists. Pleaser enter another one.')
                return redirect('users:signup')
    # when user is NOT in database
    if page_origin == FROMLOGIN:
        messages.info(request, "No corresponding account was found. Please sign-up first.")
        return redirect('users:signup')
    elif page_origin == FROMSIGNUP:
        newUser = User.objects.create_user(username_42, email_42)
        newUser.profile.isstudent = True
        newUser.profile.save()
        messages.success(request, f'Your account has been created! You are now able to log in.')
        return redirect('users:login')

@require_POST
def logout_v(request) -> None:
    if request.method == 'POST':
        user = request.user
        user.profile.active = False
        user.profile.save()
        logout(request)
        messages.info(request, f'You have been logged out.')
        return redirect('users:login')

################################################################################

"""
Profile view of current user or another one
"""
@login_required(login_url='/users/login/?redirected=true')
def profile(request, username: str) -> HttpResponse:
    context = {}
    try:
        displayed_user = User.objects.get(username=username)
    except:
        return render(request, '404.html', {
            'message': 'User not found',
            "show_alerts": True
        })
    if displayed_user:
        context['displayed_user'] = displayed_user
        context['username'] = displayed_user.username
        context['id'] = displayed_user.id
        context['email'] = displayed_user.email
        context['profile_img'] = displayed_user.profile.image.url
        context['wins'] = displayed_user.profile.wins
        context['losses'] = displayed_user.profile.losses
        context['active'] = displayed_user.profile.active
        context['description'] = displayed_user.profile.description
        context['all_users'] = User.objects.all()
        context['blocklist'] = displayed_user.profile.blocklist.all()

        try:
            friend_list = FriendList.objects.get(user=displayed_user)
        except FriendList.DoesNotExist:
            friend_list = FriendList(user=displayed_user)
            friend_list.save()
        friends = friend_list.friends.all()
        context['friends'] = friends

        # Fetch the latest matches for the displayed user
        latest_matches = LeaderboardEntry.objects.filter(user=displayed_user).order_by('-timestamp')[:10]
        context['latest_matches'] = latest_matches

        # Define template variables
        is_self = True
        is_friend = False
        request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
        friend_requests = None
        user = request.user
        # Logged in but NOT looking at your own profile
        if user.is_authenticated and user != displayed_user:
            is_self = False
            if friends.filter(pk=user.id):
                is_friend = True
            else:
                is_friend = False
                # CASE1: Request has been sent from THEM to YOU: THEM_TO_YOU
                if get_friend_request_or_false(sender=displayed_user, receiver=user) != False:
                    request_sent = FriendRequestStatus.THEM_SENT_TO_YOU.value
                    context['pending_friend_request_id'] = get_friend_request_or_false(
                        sender=displayed_user,
                        receiver=user
                    ).id
                # CASE2: Request has been sent from YOU to THEM: YOU_SENT_TO_THEM
                elif get_friend_request_or_false(sender=user, receiver=displayed_user) != False:
                    request_sent = FriendRequestStatus.YOU_SENT_TO_THEM.value
                # CASE3: No request has been sent: NO_REQUEST_SENT
                else:
                    request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
        # NOT logged in
        elif not user.is_authenticated:
            is_self = False
        # Logged in and looking at your profile
        else:
            try:
                friend_requests = FriendRequest.objects.filter(receiver=user, is_active=True)
            except:
                pass
        
        context["is_self"] = is_self
        context["is_friend"] = is_friend
        context['request_sent'] = request_sent
        context['friend_requests'] = friend_requests

    context['show_alerts'] = True

    if 'HTTP_HX_REQUEST' in request.META:
        if request.GET.get('fromEdit', 'False') == 'True':
            return render(request, 'users/profile.html', context)
        context['request'] = request
        context['my_csrf'] = get_token(request)
        b_body = render_block_to_string('users/profile.html', 'body', context)
        b_script = render_block_to_string('users/profile.html', 'script_body', context)
        return HttpResponse(b_body + b_script)

    return render(request, 'users/profile.html', context)

"""
Logic for deleting a user > profile > friendlist
"""
@login_required(login_url='/users/login/?redirected=true')
def deleteprofile(request, username: str) -> None:
    # Ensure the user is deleting their own profile or is a superuser

django/templates/users/snippets/accept_friend_request.html
<script type="text/javascript">

    function acceptFriendRequest(friend_request_id, uiUpdateFunction) {
        var url = "{% url 'users:friend_request_accept' friend_request_id=65464762465764 %}".replace(65464762465764, friend_request_id)
        $.ajax({
            type: "GET",
            dataType: "json",
            url: url,
            timaout: 5000,
            success: function(data) {
                if (data['response'] == "Friend request accepted") {

                }
                else if (data.response != null) {
                    alert(data.response)
                }
            },
            error: function(data) {
                alert("Something went wrong: " + data)
            },
            complete: function(data) {
                uiUpdateFunction()
            },
        })
    }

</script>

django/templates/users/snippets/cancel_friend_request.html
<script type="text/javascript">

    function cancelFriendRequest(id, uiUpdateFunction) {

        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "{% url 'users:friend_request_cancel' %}",
            data: payload,
            timaout: 5000,
            success: function(data) {
                if (data['response'] == "Friend request cancelled") {
                }
                else if (data.response != null) {
                    alert(data.response)
                }
            },
            error: function(data) {
                alert("Something went wrong: " + data)
            },
            complete: function(data) {
                uiUpdateFunction()
            },
        })
    }

</script>

django/templates/users/snippets/decline_friend_request.html
<script type="text/javascript">

    function declineFriendRequest(friend_request_id, uiUpdateFunction) {
        var url = "{% url 'users:friend_request_decline' friend_request_id=65464762465764 %}".replace(65464762465764, friend_request_id)
        $.ajax({
            type: "GET",
            dataType: "json",
            url: url,
            timaout: 5000,
            success: function(data) {
                if (data['response'] == "Friend request declined") {
                }
                else if (data.response != null) {
                    alert(data.response)
                }
            },
            error: function(data) {
                alert("Something went wrong: " + data)
            },
            complete: function(data) {
                uiUpdateFunction()
            },
        })
    }

</script>

django/templates/users/snippets/remove_friend.html
<script type="text/javascript">

    function removeFriend(id, uiUpdateFunction) {
        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "{% url 'users:remove_friend' %}",
            timeout: 5000,
            data: payload,
            success: function(data) {
                if (data['response'] == "Successfully removed that friend"){
                }
                else if (data['response'] != null) {
                    alert(data['response']);
                }
            },
            error: function(data) {
                alert("Something went wrong." + data)
            },
            complete: function(data) {
                uiUpdateFunction()
            }
        })
    }

</script>

django/templates/users/snippets/send_friend_request.html
<script type="text/javascript">

    function sendFriendRequest(id, uiUpdateFunction) {
        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "{% url 'users:friend_request' %}",
            timeout: 5000,
            data: payload,
            success: function(data) {
                if (data['response'] == "Friend request sent."){
                    uiUpdateFunction()
                }
                else if (data['response'] != null) {
                    alert(data['response']);
                }
            },
            error: function(data) {
                alert("Something went wrong." + data)
            },
            // complete: function(data) {
            //     // uiUpdateFunction()
            // }
        })
    }

</script>