django/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_page, name='home'),
    path('create_room/', views.create_room, name='create_room'),
	path('send_game_invite/', views.send_game_invite, name='send_game_invite'),
    path('<str:slug>/', views.room, name='room'),
]

django/game/urls.py
from django.urls import path
from .views import game, lobby, submit_game_result, join_tournament, tournament_detail, start_tournament, tournament_list, tournament_progress, play_match
from django.conf.urls.static import static
from django.conf import settings

app_name = 'game'

urlpatterns = [
	path('<int:party_id>/play_match/<int:match_id>/', game, name='game_with_match'),  # Game page with party ID and match ID
    path('<int:party_id>/', game, name='game'),  # Game page with party ID
    path('lobby/', lobby, name='lobby'),  # Lobby page
    path('submit_result/', submit_game_result, name='submit_game_result'),  # New endpoint
	
    # Tournament URLs
    path('tournaments/', tournament_list, name='tournament_list'),
    path('tournaments/<int:tournament_id>/', tournament_detail, name='tournament_detail'),
	path('tournaments/<int:tournament_id>/progress/', tournament_progress, name='tournament_progress'),
    path('tournaments/<int:tournament_id>/join/', join_tournament, name='join_tournament'),
    path('tournaments/<int:tournament_id>/start/', start_tournament, name='start_tournament'),
	path('tournaments/<int:tournament_id>/play_match/<int:match_id>/', play_match, name='play_match'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/home/urls.py
from django.urls import path
from home.views import welcome, leaderboard
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
	path('', welcome, name='welcome'),
	path('leaderboard/', leaderboard, name='leaderboard'),
]

django/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('', include('home.urls')),
    path('chat/', include('chat.urls')),
    path('users/', include('users.urls')),
    path('', include('security.urls')),
]

# to access user uploaded images (profile picture)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_v, name='signup'),
    path('blocking/', views.blocking, name='blocking'),
    path('login/', views.login_v, name='login'),
    path('callback/', views.callback, name='callback'),
    path('logout/', views.logout_v, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<str:username>', views.profile, name='profile'),
	path('profile/edit/', views.editprofile, name='profile_edit'),
    path('profile/<str:username>/delete/', views.deleteprofile, name='profile_delete'),
    path('friend_request/', views.send_friend_request, name='friend_request'),
    path('friend_remove/', views.remove_friend, name='remove_friend'),
    path('cancel_friend_request/', views.cancel_friend_request, name='friend_request_cancel'),
    path('accept_friend_request/<str:friend_request_id>', views.accept_friend_request, name='friend_request_accept'),
    path('decline_friend_request/<str:friend_request_id>', views.decline_friend_request, name='friend_request_decline'),
]

django/home/models.py
from django.db import models

class Score(models.Model):
	user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	score = models.IntegerField()
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.username + " " + str(self.score) + " " + str(self.date)

django/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth.models import User
from .models import Score
from django.http import HttpResponse
from render_block import render_block_to_string

@login_required(login_url='/users/login/?redirected=true')
def welcome(request):
	context = {
		"show_alert": True,
	}
	if 'HTTP_HX_REQUEST' in request.META:
		html = render_block_to_string('home/welcome.html', 'body', context)
		return HttpResponse(html)
	return render(request, 'home/welcome.html', context)

def leaderboard(request):
	context = {
		'all_users': User.objects.all().order_by('-profile__wins'),
	}
	if 'HTTP_HX_REQUEST' in request.META:
		html = render_block_to_string('home/leaderboard.html', 'body', context)
		return HttpResponse(html)
	return render(request, 'home/leaderboard.html', context)

django/templates/home.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}

<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/reset.css' %}">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" href="{% static 'css/lobby.css' %}">
		<link rel="stylesheet" href="{% static 'css/users.css' %}">
		{% block styles %}{% endblock %}
		<title>{% block title %}{% endblock %}</title>
		
		<script src="{% static 'js/htmx.min.js' %}" defer></script>
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		{% block script %}{% endblock %}
	</head>
	<body hx-headers='{"X-CSRFToken": "{% csrf_token %}"}' id="app-body">
        {% include './navbar.html' %}
		<main id="app-root" class="container_global">
			{% if show_alerts %}
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-{{message.tags}}">
							{{ message | safe }}
						</div>
					{% endfor %}
				{% endif %}
			{% endif %}
			{% block body %}{% endblock %}
		</main>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
		<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
		{% block script_body %}{% endblock %}
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
	</body>
</html>

django/templates/navbar.html
{% load static %}

<header class="navbar">
    <div class="container-sm mt-2 mb-2">
        <div class="row_custom">
            {% if request.user.is_authenticated %}
                <a class="logo" href="{% url 'home:welcome' %}" hx-target="#app-root">Transcendence</a>
            {% else %}
                <a class="logo" href="{% url 'home:welcome' %}">Transcendence</a>
            {% endif %}
            <nav>
                <ul class="nav_links" alt="logo">
                    
                    {% if request.user.is_authenticated %}
                        {% if request.user.is_superuser %}
                            <li><a href="/admin/" hx-target="#app-root">Admin</a></li>
                        {% endif %}
                        <li><a href="{% url 'home:welcome' %}" hx-target="#app-root">Home</a></li>
                        <li><a href="{% url 'home:leaderboard' %}" hx-target="#app-root">Leaderboard</a></li>
                        <li><a href="{% url 'game:lobby' %}" hx-target="#app-root">Game</a></li>
                        <li><a href="{% url 'game:tournament_list' %}" hx-target="#app-root">Tournaments</a></li>
                        <li><a href="{% url 'chat:home' %}" hx-target="#app-root">Chat</a></li>
                        <li><a href="{% url 'users:profile' %}{{request.user.username}}" hx-target="#app-root">Profile</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <div class="row_custom">
            {% if request.user.is_authenticated %}
            <form action="{% url 'users:logout' %}" method="post" hx-boost="false" class="sub_menu_link">
                {% csrf_token %}
                <button type="submit" class="d-flex align-items-center btn_discrete" style="margin-right: 16px;">
                    <svg style="margin-right: 8px;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z"/>
                        <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
                    </svg>
                    Logout
                </button>
            </form>
            
            <a href="{% url 'users:profile' %}{{request.user.username}}" hx-target="#app-root">
                <img class="user_pic" src="{{ request.user.profile.image.url }}" width="48px" height="48px" alt="profile image">
            </a>

            {% else %}
                <a href="{% url 'users:login' %}" hx-target="#app-body"><button class="cta">Log in</button></a>
                <a href="{% url 'users:signup' %}" hx-target="#app-body"><button class="cta">Sign up</button></a>
            {% endif %}
        </div>
    </div>
</header>